### ISSUE TITLE
Reproducability issue

### ISSUE THREAD

**Issue by christinab12** [HelmholtzAI-Consultants-Munich/Quicksetup-ai#11]
Hi,

I am not able to get reproducible results when using the pipeline, with a ResNet on a small dataset. 

Fixed by adding the following in training_pipeline under ```if config.get("seed")```:
```torch.cuda.manual_seed(config.seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.enabled = False
```

**Comment by IsraMekki0** [comment]
Closed, thanks for the feedback
